server:
  port: 8080

spring:
  application:
    name: duoclink-backend
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/duoclink}
      auto-index-creation: true

# Swagger/OpenAPI en /swagger-ui.html
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.springframework.web: INFO
    org.springframework.data.mongodb: INFO